php:
  build: .
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./public_html:/var/www/html
  links:
  - db
db:
  image: mysql:5.5
  ports:
   - "3306:3306"
  volumes:
   - "./mysql:/var/lib/mysql"
   - ".:/home/docker"
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=framework
