version: '3.1'

services:
  web:
    build:
      context: docker/.
    ports:
      - "80:80"
      - "443:443"
    links:
      - db:mysql
    working_dir: /var/www
    volumes:
      - .:/var/www
      - "./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "./docker/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - DOCUMENT_ROOT=/var/www/public
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql:/var/lib/mysql"
      - ".:/home/docker"
    environment:
      - MYSQL_DATABASE=base
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:mysql
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
